<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><UseWPF>true</UseWPF></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CJL.Shared\CJL.Shared.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
  </ItemGroup>
</Project>
